<?php
/*
  $Id$

  CE Phoenix, E-Commerce made Easy
  https://phoenixcart.org

  Copyright (c) 2021 Phoenix Cart

  Released under the GNU General Public License
*/

const NAVBAR_TITLE = 'Security Check';
const HEADING_TITLE = 'Security Check';

const TEXT_INFORMATION = <<<'EOT'
We have detected that your browser has generated a different SSL Session ID used throughout our secure pages.<br><br>
For security purposes you will need to sign in to your profile again to continue shopping.<br><br>
Some browsers do not have the capability of generating a secure SSL Session ID automatically. If you use such a browser, we recommend switching to a more modern browser such as <a href="https://www.microsoft.com/en-us/edge/download?form=MA13FJ" target="_blank" rel="noreferrer">Microsoft Edge</a> or <a  href="https://support.google.com/chrome/answer/95346" target="_blank" rel="noreferrer">Google Chrome</a> or <a href="https://www.mozilla.org/en-GB/firefox/" target="_blank" rel="noreferrer">Mozilla Firefox</a> to continue using our site.<br><br>
We have taken this security measure for your benefit, and apologize for any inconvenience caused.<br><br>
Please <a class="btn btn-success" role="button" href="%s">contact us</a> if you have any questions about this requirement.
EOT;

const BOX_INFORMATION_HEADING = 'Privacy and Security';
const BOX_INFORMATION = <<<'EOT'
We validate the SSL Session ID automatically generated by your browser on every secure page request made to this server.<br><br>
This validation assures that it is you who is navigating on this site with your profile and not somebody else.
EOT;
