<?php
/*
  $Id$

  CE Phoenix, E-Commerce made Easy
  https://phoenixcart.org

  Copyright (c) 2021 Phoenix Cart

  Released under the GNU General Public License
*/

  class ht_google_adwords_conversion extends abstract_executable_module {

    const CONFIG_KEY_BASE = 'MODULE_HEADER_TAGS_GOOGLE_ADWORDS_CONVERSION_';

    const FORMAT = [
      '1' => 'Single Line',
      '2' => 'Two Lines',
      '3' => 'No Indicator',
    ];

    public function __construct() {
      parent::__construct(__FILE__);

      if ($this->base_constant('JS_PLACEMENT') === 'Footer') {
        $this->group = 'footer_scripts';
      }
    }

    public function execute() {
      if ( isset($_SESSION['customer_id']) && (Request::get_page() === 'checkout_success.php') ) {
        $order_query = $GLOBALS['db']->query(sprintf(<<<'EOSQL'
SELECT o.orders_id, o.currency, o.currency_value, ot.value
 FROM orders o
  LEFT JOIN orders_total ot ON o.orders_id = ot.orders_id AND ot.class = 'ot_subtotal'
 WHERE o.customers_id = %d
 ORDER BY o.date_purchased DESC
 LIMIT 1
EOSQL
          , (int)$_SESSION['customer_id']));

        if ($order = $order_query->fetch_assoc()) {
          if (isset($GLOBALS['lng']) && ($GLOBALS['lng'] instanceof language)) {
            $lng = &$GLOBALS['lng'];
          } else {
            $lng = new language();
          }

          $language_code = 'en';
          foreach ($lng->catalog_languages as $lkey => $lvalue) {
            if ($lvalue['id'] == $_SESSION['languages_id']) {
              $language_code = $lkey;
              break;
            }
          }

          $conversion_id = (int)$this->base_constant('ID');
          $conversion_language = htmlspecialchars($language_code);
          $conversion_format = (int)$this->base_constant('FORMAT');
          $conversion_color = htmlspecialchars($this->base_constant('COLOR'));
          $conversion_label = htmlspecialchars($this->base_constant('LABEL'));
          $conversion_value = $GLOBALS['currencies']->format_raw($order['value'], true, $order['currency'], $order['currency_value']);

          $output = <<<"EOD"
<script>
/* <![CDATA[ */
var google_conversion_id = {$conversion_id};
var google_conversion_language = "{$conversion_language}";
var google_conversion_format = "{$conversion_format}";
var google_conversion_color = "{$conversion_color}";
var google_conversion_label = "{$conversion_label}";
var google_conversion_value = {$conversion_value};
/* ]]> */
</script>
<script src="//www.googleadservices.com/pagead/conversion.js"></script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/{$conversion_id}/?value={$conversion_value}&amp;label={$conversion_label}&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
EOD;

          $GLOBALS['Template']->add_block($output, $this->group);
        }
      }
    }

    protected function get_parameters() {
      return [
        'MODULE_HEADER_TAGS_GOOGLE_ADWORDS_CONVERSION_STATUS' => [
          'title' => 'Enable Google AdWords Conversion Module',
          'value' => 'True',
          'desc' => 'Do you want to allow the Google AdWords Conversion Module on your checkout success page?',
          'set_func' => "Config::select_one(['True', 'False'], ",
        ],
        'MODULE_HEADER_TAGS_GOOGLE_ADWORDS_CONVERSION_ID' => [
          'title' => 'Conversion ID',
          'value' => '',
          'desc' => 'The Google AdWords Conversion ID',
        ],
        'MODULE_HEADER_TAGS_GOOGLE_ADWORDS_CONVERSION_FORMAT' => [
          'title' => 'Tracking Notification Layout',
          'value' => '1',
          'desc' => 'A small message will appear on your site telling customers that their visits on your site are being tracked. We recommend you use it.',
          'set_func' => 'ht_google_adwords_conversion::set_format(',
          'use_func' => 'ht_google_adwords_conversion::get_format',
        ],
        'MODULE_HEADER_TAGS_GOOGLE_ADWORDS_CONVERSION_COLOR' => [
          'title' => 'Page Background Color',
          'value' => 'ffffff',
          'desc' => 'Enter a HTML color to match the color of your website background page.',
        ],
        'MODULE_HEADER_TAGS_GOOGLE_ADWORDS_CONVERSION_LABEL' => [
          'title' => 'Conversion Label',
          'value' => '',
          'desc' => 'The alphanumeric code generated by Google for your AdWords Conversion',
        ],
        'MODULE_HEADER_TAGS_GOOGLE_ADWORDS_CONVERSION_JS_PLACEMENT' => [
          'title' => 'Javascript Placement',
          'value' => 'Footer',
          'desc' => 'Should the Google AdWords Conversion javascript be loaded in the header or footer?',
          'set_func' => "Config::select_one(['Header', 'Footer'], ",
        ],
        'MODULE_HEADER_TAGS_GOOGLE_ADWORDS_CONVERSION_SORT_ORDER' => [
          'title' => 'Sort Order',
          'value' => '0',
          'desc' => 'Sort order of display. Lowest is displayed first.',
        ],
      ];
    }

    public static function set_format($key_value, $field_key) {
      $string = '';
      foreach ( static::FORMAT as $key => $value ) {
        $string .= '<br><input type="radio" name="configuration[' . $field_key . ']" value="' . $key . '"';

        if ($key_value == $key) {
          $string .= ' checked="checked"';
        }

        $string .= ' /> ' . $value;
      }

      return $string;
    }

    public static function get_format($value) {
      return static::FORMAT[$value];
    }

  }
